# Don't change the settings below unless you now what you are doing please
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # make the shortcodes work
  [markup.highlight]
      noClasses = false

pygmentsUseClasses = true
canonifyurls = true