# -----------------------------------------------------------------------
# Navigation menu 
# -----------------------------------------------------------------------
[[menu.nav]]
  name = "Home"
  pre = "<i class='fas fa-home la-lg'></i>"
  weight = -110 
  identifier = "home"
  url = "/"
[[menu.nav]]
  name = "Docs"
  pre = "<i class='fas fa-book la-lg'></i>"
  weight = -105 
  identifier = "docs"
  url = "/docs"

[[menu.nav]]
  name = "Categories"
  pre = "<i class='fas fa-tags fa-lg'></i> "
  weight = -90 
  identifier = "categories"
  url = "/categories"
[[menu.nav]]
  name = "About"
  pre = "<i class='fas fa-info-circle  fa-lg'></i> "
  weight = -80 
  identifier = "about"
  url = "/about"
[[menu.nav]]
  name = "Source Code"
  pre = "<i class='fab fa-github fa-lg'></i> "
  weight = -70 
  identifier = "github"
  url = "https://github.com/slashformotion/hugo-tufte"

# -----------------------------------------------------------------------
# FOOTER MENU
# If you need to add custom links to you footer: put them here. Be aware that this theme is using fontawesome. 
# Please head to https://fontawesome.com/v4.7/icons/ to pick icons
# -----------------------------------------------------------------------

[[menu.footer]]
  name = "Custom footer link"
  pre = "<i class='fab fa-google fa-lg'></i> "
  weight = -90 
  identifier = "custom_link"
  url = "https://google.com"